on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: tsugunt/hello-world-javascript-action@v1
      with:
        name: 'Sundar'
    - name: status check
      run: echo "status ${{ steps.hello.outputs.status }}"
